name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # - name: Run chart-releaser
    #   uses: helm/chart-releaser-action@v1.1.0
    #   env:
    #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Package Helm GHCR
        # You may pin to the exact commit or the version.
        # uses: explorium-ai/package-helm-ghcr-action@60069b348ae635066398746368176daa56a06956
        uses: camposdelima/package-helm-ghcr-action@v1.0.2-charlie
        with:
          # Github token to authenticate to Repo
          gh-token: "${{ secrets.GITHUB_TOKEN }}"
          # Github Repo Owner to deploy to
          #gh-repo-owner: "${{ github.actor }}" # optional
          # the directory path to the specified chart
          #chart-path: "."
